[font]
size = 16.0
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold"  }
italic = { family = "Iosevka Term", style = "Italic"  }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }

[mouse]
hide_when_typing = true

[window]
padding = { x = 0, y = 8 }

